### PR TITLE
BREAKING CHANGE: Amend version identifier in ID

### PR DESCRIPTION
**Pull request by podedra92**
Amend the version identifier from `publisher.extension-version` to `publisher.extension@1.0.0`.
In an effort to address #23 

*Note:* This is a breaking change as it amends the extension ID and so will change the way extensions are removed from Code Marketplace

### CODE REVIEW

**Comment by podedra92** [comment]
recheck

**Comment by podedra92** [comment]
recheck

**Comment by podedra92** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by code-asher — APPROVED** [review]
Thank you!

**Pull request merged**
